# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(582, 381)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 70, 431, 227))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.kind = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.kind.setObjectName("kind")
        self.gridLayout.addWidget(self.kind, 0, 1, 1, 1)
        self.send_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.send_btn.setObjectName("send_btn")
        self.gridLayout.addWidget(self.send_btn, 7, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.degree = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.degree.setObjectName("degree")
        self.gridLayout.addWidget(self.degree, 1, 1, 1, 1)
        self.desc = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.desc.setObjectName("desc")
        self.gridLayout.addWidget(self.desc, 3, 1, 1, 1)
        self.volume = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.volume.setObjectName("volume")
        self.gridLayout.addWidget(self.volume, 5, 1, 1, 1)
        self.type = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.type.setObjectName("type")
        self.gridLayout.addWidget(self.type, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.price = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.price.setObjectName("price")
        self.gridLayout.addWidget(self.price, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setStyleSheet("color: red;")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "packing volume"))
        self.label_5.setText(_translate("Dialog", "price"))
        self.send_btn.setText(_translate("Dialog", "Отправить"))
        self.label_3.setText(_translate("Dialog", "ground / in grains"))
        self.label_2.setText(_translate("Dialog", "degree of roast"))
        self.label.setText(_translate("Dialog", "kind"))
        self.label_4.setText(_translate("Dialog", "taste description"))
        self.label_7.setText(_translate("Dialog", "Заполните все поля!"))
